### ISSUE TITLE
converter.py issue

### ISSUE THREAD

**Issue by RouatbiH** [zhouhang95/neox_tools#2]
Game : Creative Destruction
File : char.npk (files exported by quickbms)

```
C:\Users\*******\Desktop\cdskins>python converter.py char/00000024.mesh
Traceback (most recent call last):
  File "converter.py", line 572, in <module>
    main()
  File "converter.py", line 568, in main
    savepmx(model, opt.path)
  File "converter.py", line 295, in savepmx
    center_index = add_bone(pmx_model, center_bone, waist_index)
  File "converter.py", line 253, in add_bone
    assert index <= len(pmxm.bones)
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```

```
C:\Users\*******\Desktop\cdskins>python converter.py char/00000024.mesh --mode iqe
Traceback (most recent call last):
  File "converter.py", line 572, in <module>
    main()
  File "converter.py", line 566, in main
    saveiqe(model, opt.path)
  File "converter.py", line 50, in saveiqe
    for i in range(bone_count):
NameError: name 'bone_count' is not defined
```

**Comment by RouatbiH** [comment]
`python converter.py char/00000024.mesh --mode obj`
work fine

**Comment by zhouhang95** [comment]
Some mesh doesn't have bones. Just save obj is ok.
